pipeline {
    agent any

    tools {
        maven 'maven-3'
    }

    stages {
        stage('Build & Test notification-service') {
            steps {
                sh 'mvn -B -pl notification-service -am clean package -DskipTests'
                sh 'mvn -B -pl notification-service -am test'
            }
        }

        stage('Archive notification-service JAR') {
            steps {
                archiveArtifacts artifacts: 'notification-service/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo '✅ notification-service build SUCCESS bro!'
        }
        failure {
            echo '❌ notification-service build FAILED.'
        }
    }
}
