pipeline {
    agent any

    tools {
        maven 'maven-3'
    }

    stages {
        stage('Build & Test car-listing-service') {
            steps {
                sh 'mvn -B -pl car-listing-service -am clean package -DskipTests'
                sh 'mvn -B -pl car-listing-service -am test'
            }
        }

        stage('Archive car-listing-service JAR') {
            steps {
                archiveArtifacts artifacts: 'car-listing-service/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo '✅ car-listing-service build SUCCESS bro!'
        }
        failure {
            echo '❌ car-listing-service build FAILED.'
        }
    }
}
