pipeline {
    agent any

    tools {
        maven 'maven-3'
    }

    stages {
        stage('Build & Test discovery-service') {
            steps {
                sh 'mvn -B -pl discovery-service -am clean package -DskipTests'
                sh 'mvn -B -pl discovery-service -am test'
            }
        }

        stage('Archive discovery-service JAR') {
            steps {
                archiveArtifacts artifacts: 'discovery-service/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo '✅ discovery-service build SUCCESS bro!'
        }
        failure {
            echo '❌ discovery-service build FAILED.'
        }
    }
}
